sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update; true
before_script:
  - pwd > /tmp/old_current_path
  - sudo -i -E perl src/fastnetmon_install.pl --use-git-master
  - cd `cat /tmp/old_current_path`
  - cd src
script: mkdir -p build; cd build; cmake ..; make
notifications:
  email:
    recipients:
      - pavel.odintsov@gmail.com
    on_success: change
    on_failure: always
